CR EQU 0DH
LF EQU 0AH
STACK SEGMENT
DW 100 DUP(?)
STACK ENDS
DATA SEGMENT
STRING DB 'mp'
DB CR,LF,'$'
STRLEN DW 05H
MESSAGE1 DB ' THE ORIGINAL STRING:','$'
DB CR,LF,'$'
MESSAGE2 DB ' THE TRANSLATEDSTRING:','$'
TABLE DB 48 DUP(' '), '0123456789', 9 DUP(' ')
DB 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 6 dup(' ')
DB 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 133 dup(' ')
DATA ENDS
CODE SEGMENT
Assume CS:CODE, DS:DATA
START: MOV AX,DATA
MOV DS,AX
MOV ES,AX
LEA SI,STRING
LEA DI,STRING
LEA BX,TABLE
MOV CX, STRLEN
MOV AH,09H
LEA DX, MESSAGE1
INT 21H
MOV AH,09H
LEA DX, STRING
INT 21H
CLD
TOP: LODSB
XLAT
STOSB
LOOP TOP
MOV AH,09H
LEA DX, MESSAGE2
INT 21H
MOV AH,09H
LEA DX, STRING
INT 21H
QUIT: MOV AL,0
MOV AH,04CH
INT 21H
CODE ENDS
END START
